[package]
name = "nexbot_recorder_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.16.0"
borsh = "0.9"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
